### ISSUE TITLE
Buy Run Packs for adults

### ISSUE THREAD

**Issue by matthewdeanmartin** [matthewdeanmartin/run_2023#2]

**Comment by pianoelle** [comment]
- [ ] $125 for 4 Race Entires.
(up to a $115 savings). Includes swag or 4 race shirts

- [ ] $250 for 4 Race Entires and a Pair of Shoes.
(up to a $140 savings). Includes swag or 4 race shirts. PLUS a pair of shoes from PR ($150 store credit)
